bind 127.0.0.1
port 6691
protected-mode yes
daemonize no
supervised no
databases 1
aclfile "/Library/Application Support/SubmarineDashRedis/users.acl"
dir "/Library/Application Support/SubmarineDashRedis/data"
dbfilename dump.rdb
save 3600 1
save 300 100
save 60 10000
appendonly yes
appendfilename appendonly.aof
appenddirname appendonlydir
appendfsync always
aof-use-rdb-preamble yes
no-appendfsync-on-rewrite no
maxmemory 512mb
maxmemory-policy noeviction
loglevel notice
logfile ""
